name: Build and deploy LE-WEBAPP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --legacy-peer-deps
      - run: npm run build
      - run: echo ${github.event.pull_request.merged}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::689954339495:role/github-role-push-to-le-bucket
          aws-region: ap-south-1
          role-session-name: GithubActionsSession
      
      # Copying the build files to S3 Bucket
      - name: Copy files to S3 bucket with the AWS CLI
        run: aws s3 sync dist/levitating s3://levitatingelephant.com

      # Clears the Cloudfront Cache
      - name: Create Invalidation - Cloudfront
        run: aws cloudfront create-invalidation --distribution-id E907GFFRUMV3 --paths "/*"